
// This file has been generated by the GUI designer. Do not modify.
namespace LinuxClient.Dialogs
{
	public partial class LoginDialog
	{
		private global::Gtk.VBox vbox2;
		
		private global::Gtk.HBox hbox1;
		
		private global::Gtk.Label UsernameLabel;
		
		private global::Gtk.Entry UsernameLineEdit;
		
		private global::Gtk.HBox hbox2;
		
		private global::Gtk.Label ServerLabel;
		
		private global::Gtk.Entry ServerLineEdit;
		
		private global::Gtk.HBox hbox3;
		
		private global::Gtk.Label PasswortLabel;
		
		private global::Gtk.Entry PasswordLineEdit;
		
		private global::Gtk.Button buttonCancel;
		
		private global::Gtk.Button buttonOk;

		protected virtual void Build ()
		{
			global::Stetic.Gui.Initialize (this);
			// Widget LinuxClient.Dialogs.LoginDialog
			this.Name = "LinuxClient.Dialogs.LoginDialog";
			this.Title = global::Mono.Unix.Catalog.GetString ("dialog1");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Internal child LinuxClient.Dialogs.LoginDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox ();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox ();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.UsernameLabel = new global::Gtk.Label ();
			this.UsernameLabel.Name = "UsernameLabel";
			this.UsernameLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Username");
			this.hbox1.Add (this.UsernameLabel);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.UsernameLabel]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.UsernameLineEdit = new global::Gtk.Entry ();
			this.UsernameLineEdit.CanFocus = true;
			this.UsernameLineEdit.Name = "UsernameLineEdit";
			this.UsernameLineEdit.IsEditable = true;
			this.UsernameLineEdit.InvisibleChar = '•';
			this.hbox1.Add (this.UsernameLineEdit);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1 [this.UsernameLineEdit]));
			w3.Position = 1;
			this.vbox2.Add (this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox1]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox ();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ServerLabel = new global::Gtk.Label ();
			this.ServerLabel.Name = "ServerLabel";
			this.ServerLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Server");
			this.hbox2.Add (this.ServerLabel);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.ServerLabel]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.ServerLineEdit = new global::Gtk.Entry ();
			this.ServerLineEdit.CanFocus = true;
			this.ServerLineEdit.Name = "ServerLineEdit";
			this.ServerLineEdit.IsEditable = true;
			this.ServerLineEdit.InvisibleChar = '•';
			this.hbox2.Add (this.ServerLineEdit);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox2 [this.ServerLineEdit]));
			w6.Position = 1;
			this.vbox2.Add (this.hbox2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox2]));
			w7.Position = 1;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox ();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.PasswortLabel = new global::Gtk.Label ();
			this.PasswortLabel.Name = "PasswortLabel";
			this.PasswortLabel.LabelProp = global::Mono.Unix.Catalog.GetString ("Passwort");
			this.hbox3.Add (this.PasswortLabel);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.PasswortLabel]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.PasswordLineEdit = new global::Gtk.Entry ();
			this.PasswordLineEdit.CanFocus = true;
			this.PasswordLineEdit.Name = "PasswordLineEdit";
			this.PasswordLineEdit.IsEditable = true;
			this.PasswordLineEdit.Visibility = false;
			this.PasswordLineEdit.InvisibleChar = '•';
			this.hbox3.Add (this.PasswordLineEdit);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox3 [this.PasswordLineEdit]));
			w9.Position = 1;
			this.vbox2.Add (this.hbox3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2 [this.hbox3]));
			w10.Position = 2;
			w10.Expand = false;
			w10.Fill = false;
			w1.Add (this.vbox2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(w1 [this.vbox2]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Internal child LinuxClient.Dialogs.LoginDialog.ActionArea
			global::Gtk.HButtonBox w12 = this.ActionArea;
			w12.Name = "dialog1_ActionArea";
			w12.Spacing = 10;
			w12.BorderWidth = ((uint)(5));
			w12.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonCancel = new global::Gtk.Button ();
			this.buttonCancel.CanDefault = true;
			this.buttonCancel.CanFocus = true;
			this.buttonCancel.Name = "buttonCancel";
			this.buttonCancel.UseStock = true;
			this.buttonCancel.UseUnderline = true;
			this.buttonCancel.Label = "gtk-cancel";
			this.AddActionWidget (this.buttonCancel, -6);
			global::Gtk.ButtonBox.ButtonBoxChild w13 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12 [this.buttonCancel]));
			w13.Expand = false;
			w13.Fill = false;
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button ();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget (this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w14 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w12 [this.buttonOk]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			if ((this.Child != null)) {
				this.Child.ShowAll ();
			}
			this.DefaultWidth = 350;
			this.DefaultHeight = 138;
			this.Show ();
			this.buttonCancel.Clicked += new global::System.EventHandler (this.onCancelClicked);
			this.buttonOk.Clicked += new global::System.EventHandler (this.onOkClicked);
		}
	}
}
