
// This file has been generated by the GUI designer. Do not modify.
namespace LinuxClient
{
	public partial class DialogState
	{
		public virtual void Build ()
		{
			// Action group LinuxClient.DialogState
		}
	}
}
