language: csharp
solution: win32/XMPP Client.sln
install:
  - sudo apt-get install -y gtk-sharp2
  - nuget restore win32/XMPP Client.sln
script:
  - xbuild /p:Configuration=Release win32/XMPP Client.sln
  - mono ./packages/xunit.runners.*/tools/xunit.console.clr4.exe ./bin/TestModel.dll