version: 17.02.{build}
build:
  project: ./win32/Windows-Client.sln
  verbosity: minimal
artifacts:
- path: ./bin/*
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false